AWSTemplateFormatVersion: '2010-09-09'
Description: Crear politicas de bucket para permitir acceso a una cuenta especifica.

Resources:
  BucketPolicy1:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: nombre-bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::IDCuentaORIGEN:root"
            Action:
              - "s3:PutObject"
              - "s3:GetObjectAcl"
            Resource:
              - "arn:aws:s3:::nombre-bucket/*"
              - "arn:aws:s3:::nombre-bucket